### PR TITLE
Small line edit for the new user tutorial

### PR DESCRIPTION
**Pull request by btbristow**
A minor update to step 1 of the new user tutorial. This PR contains two commits, since I changed my mind about the wording.

### CODE REVIEW

**Review by rbwatson — CHANGES_REQUESTED** [review]
Can you squash these commits, please?

**Comment by btbristow** [comment]
> Can you squash these commits, please?

Hi Bob, this gave me fits for quite some time in Vim and I got this error: `cannot 'squash' without a previous commit`

I wasn't sure whether to squash two commits or one. I'm not sure this worked when I just squashed one. Hopefully we'll be able to touch base.

**Comment by rbwatson** [comment]
Sorry to hear you're having trouble. 
I posted a couple of videos in Canvas (Check the recent announcement).
They describe the squash process using the command line.
Another option is to squash the commits in the GitHub Desktop, which is a bit easier than using VIM.

**Comment by btbristow** [comment]
Hi @rbwatson I'm closing this PR as my local fork got confusing when I did a `git rebase main` as per the first video. I ended up with 17 new commits on top of my two commits. 

I'll submit a fresh single-commit PR in a moment.

**Pull request closed without merging**
