### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by radhikasundararaman24**
RS: Adding my commits to to-do-repo in the homework branch.

### CODE REVIEW

**Comment by radhikasundararaman24** [comment]
Adds to the original repo.

**Review by rbwatson — DISMISSED** [review]

**Comment by rbwatson** [comment]
Please resolve the conflicts in your feature branch.
It looks like you might just need to update your fork's main branch and rebase the feature branch.
Thanks!

**Comment by radhikasundararaman24** [comment]
Bob,
I tried following your video and ended up resolving the conflict. But, I
have some basic questions as I am doing this for the first time. Can you
please advise?

- First of all, I'm using GitHubDesktop while your videos show the command
line. I'm not able to find the equivalent command-action on GitHubDesktop.
So do you only recommend using the command line going forward?
- Why do you use a new branch called "rebase-example"? We were supposed to
work on the "Homework branch" right? As a continuation to last week's
commits are coming from this branch and also the merge conflict was coming
from this branch only. I wasn't sure- but as per that video I created
another branch - called the "rebase branch" and tried to resolve that one
conflict.

Thanks,
Radhika

**Comment by rbwatson** [comment]
This looks like it was redone in #31, so I'm closing this and merging #31

**Pull request closed without merging**
