### PR TITLE
S rose markdown test

### PR DESCRIPTION
**Pull request by shellyannrose**

### CODE REVIEW

**Review by rbwatson — COMMENTED** [review]
Can you squash these commits, please?

**Comment by shellyannrose** [comment]
> Can you squash these commits, please?

Hi Rob, I found the slide with the term squash commits, but I can't find the slide or video of how to do that. Can you point me to the slide or video that shows how to squash a commit? Thanks.

**Comment by rbwatson** [comment]
Hi Shellyann,

It took me a couple of days to put them together, but this announcement has the links to the videos that explain what to do: https://canvas.uw.edu/courses/1715843/discussion_topics/8908276

--Bob

**Review by rbwatson — APPROVED** [review]
LGTM

**Pull request merged**
