### PR TITLE
Created update-a-task.md

### PR DESCRIPTION
**Pull request by cherylkc**

### CODE REVIEW

**Review by rbwatson — CHANGES_REQUESTED** [review]
This looks ready to go.

You'll need to add a link to this topic in another topic so that people can access your new topic. Please add a link to somewhere that makes sense and it'll be ready to go.

Thanks.

**Comment by cherylkc** [comment]
I added this topic's link to the Tutorials section in index.md.

**Comment by cherylkc** [comment]
My second attempt to fix the numbered list in the deployed page also seems to have been unsuccessful. Now trying to squash all the commits.

**Comment by cherylkc** [comment]
I'm unable to squash the commits because of a merge commit. Should I force push?

**Comment by rbwatson** [comment]
If you sync your fork and update (pull) the main branch on your clone, that should clear out the merge branch and let you squash the remaining commits. (I just tried it on my system).

**Comment by rbwatson** [comment]
Closed in error. 
Reopened to complete and merge.

**Comment by cherylkc** [comment]
Pulling the main branch on my clone didn't clear the merge branch. Could I 'revert changes' in that merge branch commit or will that break everything altogether?

**Review by rbwatson — APPROVED** [review]
Rebased and squashed for merge.
LGTM.

**Pull request merged**
